spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/rent_car}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
